# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
        with:
          ref: Git-Management-Tool
          persist-credentials: true # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '11'
      - name: list file
        run: ls -l > $GITHUB_WORKSPACE/a.txt
       # Delete files in Reports folder
      - name: Remove File
        run: rm -rf $GITHUB_WORKSPACE/Reports/*
      
       # Runs a total analysic command
      - name: Run total analysic
        run: java -jar $GITHUB_WORKSPACE/Library/em-testcasemng-tool-1.0.0.jar -a -f $GITHUB_WORKSPACE/Tests -o $GITHUB_WORKSPACE/Reports
        
       # Runs a historical analysic command
      - name: Run historical analysic
        run: java -jar $GITHUB_WORKSPACE/Library/em-testcasemng-tool-1.0.0.jar -a -h -f $GITHUB_WORKSPACE/Tests -o $GITHUB_WORKSPACE/Reports
        
       # Convert Markdown to Excel
      - name: Convert Markdown to Excel
        run: java -jar $GITHUB_WORKSPACE/Library/em-testcasemng-tool-1.0.0.jar -c -m2e -f $GITHUB_WORKSPACE/Tests -o $GITHUB_WORKSPACE/Reports
       
      # Commit changes s
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          branch: Git-Management-Tool
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: Generate Results
